name: pve-kernel去分区内核编译

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false

    steps:
      - name: clone proxmox/pve-kernel
        run: |
          git clone https://github.com/proxmox/pve-kernel.git
          echo "克隆完成"
          mv ./pve-kernel/* ./
          rm -rf ./pve-kernel
        

      - name: 准备构建环境
        run: |
          rm -rf ./patches/kernel/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch
          curl -o ./patches/kernel/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch https://raw.githubusercontent.com/ybin116/build_pve_kernel_unIOMMU/main/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch

      - name: 编译
        run: |
          make


      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: pve-kernel
          path: ./*.deb
          if-no-files-found: error
